In [1]:
import pandas as pd
df = pd.read_csv("/content/drive/MyDrive/MSME Project Datasets/District wise bank of credit NCBs.csv")
df

,Country,State,District,Year,Region,Population Group,New Bank Group,Occupation Group,Occupation Sub- Group,"Number Of Accounts Of Scheduled Commercial Banks (Scbs) (UOM:Number), Scaling Factor:1","Credit Limit Of Scheduled Commercial Banks (Scbs) (UOM:INR(IndianRupees)), Scaling Factor:10000000","Outstanding Amount Of Scheduled Commercial Banks (Scbs) (UOM:INR(IndianRupees)), Scaling Factor:10000000"
0,India,Andaman and Nicobar Islands,Nicobars,"Financial Year (Apr - Mar), 2025",Eastern Region,Semi-Urban,Public Sector Banks,Personal Loans,Consumer Durables,1.0,0.0069,0.0001
1,India,Andaman and Nicobar Islands,Nicobars,"Financial Year (Apr - Mar), 2025",Eastern Region,Semi-Urban,Public Sector Banks,Personal Loans,Education,1.0,0.0700,0.0306
2,India,Andaman and Nicobar Islands,Nicobars,"Financial Year (Apr - Mar), 2025",Eastern Region,Semi-Urban,Public Sector Banks,Personal Loans,Others,683.0,52.8669,37.9677
3,India,Andaman and Nicobar Islands,Nicobars,"Financial Year (Apr - Mar), 2025",Eastern Region,Semi-Urban,Public Sector Banks,Personal Loans,Vehicles,20.0,1.4680,0.4183
4,India,Andaman and Nicobar Islands,Nicobars,"Financial Year (Apr - Mar), 2025",Eastern Region,Semi-Urban,Public Sector Banks,Industry,Textiles,1.0,0.1050,0.0978
...,...,...,...,...,...,...,...,...,...,...,...,...
2844693,India,West Bengal,Uttar Dinajpur,"Financial Year (Apr - Mar), 2010",Eastern Region,Rural,State Bank Of India And Its Associates,Finance,NaN,0.0,0.0000,0.0000
2844694,India,West Bengal,Uttar Dinajpur,"Financial Year (Apr - Mar), 2010",Eastern Region,Rural,State Bank Of India And Its Associates,Agriculture,Direct Finance,8546.0,30.6167,24.9897
2844695,India,West Bengal,Uttar Dinajpur,"Financial Year (Apr - Mar), 2010",Eastern Region,Rural,State Bank Of India And Its Associates,Agriculture,Indirect Finance,320.0,7.2763,6.7290
2844696,India,West Bengal,Uttar Dinajpur,"Financial Year (Apr - Mar), 2010",Eastern Region,Rural,State Bank Of India And Its Associates,Transport Operators,NaN,17.0,0.4439,0.3567
2844697,India,West Bengal,Uttar Dinajpur,"Financial Year (Apr - Mar), 2010",Eastern Region,Rural,State Bank Of India And Its Associates,All Others,NaN,70.0,0.4542,0.3672

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2844698 entries, 0 to 2844697
Data columns (total 12 columns):
 #   Column                                                                                                    Dtype
---  ------                                                                                                    -----
 0   Country                                                                                                   object
 1   State                                                                                                     object
 2   District                                                                                                  object
 3   Year                                                                                                      object
 4   Region                                                                                                    object
 5   Population Group                                                                                          object
 6   New Bank Group                                                                                            object
 7   Occupation Group                                                                                          object
 8   Occupation Sub- Group                                                                                     object
 9   Number Of Accounts Of Scheduled Commercial Banks (Scbs)  (UOM:Number), Scaling Factor:1                   float64
 10  Credit Limit Of Scheduled Commercial Banks (Scbs) (UOM:INR(IndianRupees)), Scaling Factor:10000000        float64
 11  Outstanding Amount Of Scheduled Commercial Banks (Scbs) (UOM:INR(IndianRupees)), Scaling Factor:10000000  float64
dtypes: float64(3), object(9)
memory usage: 260.4+ MB

In [3]:
df.tail()

,Country,State,District,Year,Region,Population Group,New Bank Group,Occupation Group,Occupation Sub- Group,"Number Of Accounts Of Scheduled Commercial Banks (Scbs) (UOM:Number), Scaling Factor:1","Credit Limit Of Scheduled Commercial Banks (Scbs) (UOM:INR(IndianRupees)), Scaling Factor:10000000","Outstanding Amount Of Scheduled Commercial Banks (Scbs) (UOM:INR(IndianRupees)), Scaling Factor:10000000"
2844693,India,West Bengal,Uttar Dinajpur,"Financial Year (Apr - Mar), 2010",Eastern Region,Rural,State Bank Of India And Its Associates,Finance,NaN,0.0,0.0000,0.0000
2844694,India,West Bengal,Uttar Dinajpur,"Financial Year (Apr - Mar), 2010",Eastern Region,Rural,State Bank Of India And Its Associates,Agriculture,Direct Finance,8546.0,30.6167,24.9897
2844695,India,West Bengal,Uttar Dinajpur,"Financial Year (Apr - Mar), 2010",Eastern Region,Rural,State Bank Of India And Its Associates,Agriculture,Indirect Finance,320.0,7.2763,6.7290
2844696,India,West Bengal,Uttar Dinajpur,"Financial Year (Apr - Mar), 2010",Eastern Region,Rural,State Bank Of India And Its Associates,Transport Operators,NaN,17.0,0.4439,0.3567
2844697,India,West Bengal,Uttar Dinajpur,"Financial Year (Apr - Mar), 2010",Eastern Region,Rural,State Bank Of India And Its Associates,All Others,NaN,70.0,0.4542,0.3672

In [4]:
finance_yr_data = df["Year"].unique()
finance_yr_data

array(['Financial Year (Apr - Mar), 2025',
       'Financial Year (Apr - Mar), 2024',
       'Financial Year (Apr - Mar), 2023',
       'Financial Year (Apr - Mar), 2022',
       'Financial Year (Apr - Mar), 2021',
       'Financial Year (Apr - Mar), 2020',
       'Financial Year (Apr - Mar), 2019',
       'Financial Year (Apr - Mar), 2018',
       'Financial Year (Apr - Mar), 2017',
       'Financial Year (Apr - Mar), 2016',
       'Financial Year (Apr - Mar), 2015',
       'Financial Year (Apr - Mar), 2014',
       'Financial Year (Apr - Mar), 2013',
       'Financial Year (Apr - Mar), 2012',
       'Financial Year (Apr - Mar), 2011',
       'Financial Year (Apr - Mar), 2010'], dtype=object)

In [5]:
df25 = df.loc[df["Year"] == "Financial Year (Apr - Mar), 2025" , ]

In [6]:
df25.shape

(177694, 12)

In [7]:
df25

,Country,State,District,Year,Region,Population Group,New Bank Group,Occupation Group,Occupation Sub- Group,"Number Of Accounts Of Scheduled Commercial Banks (Scbs) (UOM:Number), Scaling Factor:1","Credit Limit Of Scheduled Commercial Banks (Scbs) (UOM:INR(IndianRupees)), Scaling Factor:10000000","Outstanding Amount Of Scheduled Commercial Banks (Scbs) (UOM:INR(IndianRupees)), Scaling Factor:10000000"
0,India,Andaman and Nicobar Islands,Nicobars,"Financial Year (Apr - Mar), 2025",Eastern Region,Semi-Urban,Public Sector Banks,Personal Loans,Consumer Durables,1.0,0.0069,0.0001
1,India,Andaman and Nicobar Islands,Nicobars,"Financial Year (Apr - Mar), 2025",Eastern Region,Semi-Urban,Public Sector Banks,Personal Loans,Education,1.0,0.0700,0.0306
2,India,Andaman and Nicobar Islands,Nicobars,"Financial Year (Apr - Mar), 2025",Eastern Region,Semi-Urban,Public Sector Banks,Personal Loans,Others,683.0,52.8669,37.9677
3,India,Andaman and Nicobar Islands,Nicobars,"Financial Year (Apr - Mar), 2025",Eastern Region,Semi-Urban,Public Sector Banks,Personal Loans,Vehicles,20.0,1.4680,0.4183
4,India,Andaman and Nicobar Islands,Nicobars,"Financial Year (Apr - Mar), 2025",Eastern Region,Semi-Urban,Public Sector Banks,Industry,Textiles,1.0,0.1050,0.0978
...,...,...,...,...,...,...,...,...,...,...,...,...
177689,India,West Bengal,Uttar Dinajpur,"Financial Year (Apr - Mar), 2025",Eastern Region,Rural,Small Finance Banks,Professional And Other Services,"Tourism, Hotel & Restaurants",3.0,0.0094,0.0094
177690,India,West Bengal,Uttar Dinajpur,"Financial Year (Apr - Mar), 2025",Eastern Region,Rural,Small Finance Banks,Agriculture,Direct Finance,9818.0,24.6425,24.6495
177691,India,West Bengal,Uttar Dinajpur,"Financial Year (Apr - Mar), 2025",Eastern Region,Rural,Small Finance Banks,Agriculture,Indirect Finance,297.0,0.9317,0.9318
177692,India,West Bengal,Uttar Dinajpur,"Financial Year (Apr - Mar), 2025",Eastern Region,Rural,Small Finance Banks,Transport Operators,NaN,5.0,0.4935,0.4973
177693,India,West Bengal,Uttar Dinajpur,"Financial Year (Apr - Mar), 2025",Eastern Region,Rural,Small Finance Banks,All Others,NaN,9.0,0.1563,0.1563

In [8]:
df25.drop("Country" , axis = 1)

,State,District,Year,Region,Population Group,New Bank Group,Occupation Group,Occupation Sub- Group,"Number Of Accounts Of Scheduled Commercial Banks (Scbs) (UOM:Number), Scaling Factor:1","Credit Limit Of Scheduled Commercial Banks (Scbs) (UOM:INR(IndianRupees)), Scaling Factor:10000000","Outstanding Amount Of Scheduled Commercial Banks (Scbs) (UOM:INR(IndianRupees)), Scaling Factor:10000000"
0,Andaman and Nicobar Islands,Nicobars,"Financial Year (Apr - Mar), 2025",Eastern Region,Semi-Urban,Public Sector Banks,Personal Loans,Consumer Durables,1.0,0.0069,0.0001
1,Andaman and Nicobar Islands,Nicobars,"Financial Year (Apr - Mar), 2025",Eastern Region,Semi-Urban,Public Sector Banks,Personal Loans,Education,1.0,0.0700,0.0306
2,Andaman and Nicobar Islands,Nicobars,"Financial Year (Apr - Mar), 2025",Eastern Region,Semi-Urban,Public Sector Banks,Personal Loans,Others,683.0,52.8669,37.9677
3,Andaman and Nicobar Islands,Nicobars,"Financial Year (Apr - Mar), 2025",Eastern Region,Semi-Urban,Public Sector Banks,Personal Loans,Vehicles,20.0,1.4680,0.4183
4,Andaman and Nicobar Islands,Nicobars,"Financial Year (Apr - Mar), 2025",Eastern Region,Semi-Urban,Public Sector Banks,Industry,Textiles,1.0,0.1050,0.0978
...,...,...,...,...,...,...,...,...,...,...,...
177689,West Bengal,Uttar Dinajpur,"Financial Year (Apr - Mar), 2025",Eastern Region,Rural,Small Finance Banks,Professional And Other Services,"Tourism, Hotel & Restaurants",3.0,0.0094,0.0094
177690,West Bengal,Uttar Dinajpur,"Financial Year (Apr - Mar), 2025",Eastern Region,Rural,Small Finance Banks,Agriculture,Direct Finance,9818.0,24.6425,24.6495
177691,West Bengal,Uttar Dinajpur,"Financial Year (Apr - Mar), 2025",Eastern Region,Rural,Small Finance Banks,Agriculture,Indirect Finance,297.0,0.9317,0.9318
177692,West Bengal,Uttar Dinajpur,"Financial Year (Apr - Mar), 2025",Eastern Region,Rural,Small Finance Banks,Transport Operators,NaN,5.0,0.4935,0.4973
177693,West Bengal,Uttar Dinajpur,"Financial Year (Apr - Mar), 2025",Eastern Region,Rural,Small Finance Banks,All Others,NaN,9.0,0.1563,0.1563

In [9]:
df25['Occupation Group'].unique()

array(['Personal Loans', 'Industry', 'Trade', 'Agriculture',
       'Transport Operators', 'All Others',
       'Professional And Other Services', 'Finance'], dtype=object)

In [10]:
df25['Occupation Sub- Group'].unique()

array(['Consumer Durables', 'Education', 'Others', 'Vehicles', 'Textiles',
       'Retail Trade', 'Direct Finance', nan, 'Construction',
       'Engineering', 'Other Industries',
       'Vehicles,Vehicle Parts & Transport Equipments',
       'Tourism, Hotel & Restaurants', 'Indirect Finance',
       'Personal Credit Cards', 'Housing',
       'Basic Metals & Metal Products', 'Beverage & Tobacco',
       'Chemicals & Chemical Products', 'Electricity, Gas & Water',
       'Food Manufacturing & Processing', 'Gems And Jewellery',
       'Manufacture Of Cement & Cement Products', 'Mining & Quarrying',
       'Paper, Paper Products & Printing', 'Woods And Wood Products',
       'Wholesale Trade', 'It And Telecommunications',
       'Professional Services', 'Recreation Services',
       'Leather & Leather Products', 'Rubber & Plastic Products',
       'Petroleum, Coal Products & Nuclear Fuels'], dtype=object)

In [11]:
df26 = df25[df25["Occupation Group"].isin(['Industry', 'Trade', 'Transport Operators', 'Professional And Other Services'])]

In [12]:
print(df26.columns.tolist())

['Country', 'State', 'District', 'Year', 'Region', 'Population Group', 'New Bank Group', 'Occupation Group', 'Occupation Sub- Group', 'Number Of Accounts Of Scheduled Commercial Banks (Scbs)  (UOM:Number), Scaling Factor:1', 'Credit Limit Of Scheduled Commercial Banks (Scbs) (UOM:INR(IndianRupees)), Scaling Factor:10000000', 'Outstanding Amount Of Scheduled Commercial Banks (Scbs) (UOM:INR(IndianRupees)), Scaling Factor:10000000']

In [13]:
df27 = df26.drop(['Country', 'Year', 'Region', 'Population Group', 'New Bank Group', 'Occupation Sub- Group', 'Number Of Accounts Of Scheduled Commercial Banks (Scbs)  (UOM:Number), Scaling Factor:1', 'Credit Limit Of Scheduled Commercial Banks (Scbs) (UOM:INR(IndianRupees)), Scaling Factor:10000000'] , axis = 1 )

In [14]:
df27

,State,District,Occupation Group,"Outstanding Amount Of Scheduled Commercial Banks (Scbs) (UOM:INR(IndianRupees)), Scaling Factor:10000000"
4,Andaman and Nicobar Islands,Nicobars,Industry,0.0978
5,Andaman and Nicobar Islands,Nicobars,Trade,2.1265
7,Andaman and Nicobar Islands,Nicobars,Transport Operators,0.4751
12,Andaman and Nicobar Islands,Nicobars,Industry,0.3935
13,Andaman and Nicobar Islands,Nicobars,Industry,0.0708
...,...,...,...,...
177686,West Bengal,Uttar Dinajpur,Trade,0.2788
177687,West Bengal,Uttar Dinajpur,Professional And Other Services,0.0101
177688,West Bengal,Uttar Dinajpur,Professional And Other Services,6.3039
177689,West Bengal,Uttar Dinajpur,Professional And Other Services,0.0094
177692,West Bengal,Uttar Dinajpur,Transport Operators,0.4973

In [15]:
df28 = df27.rename(columns={'Outstanding Amount Of Scheduled Commercial Banks (Scbs) (UOM:INR(IndianRupees)), Scaling Factor:10000000':'Credit Crores'})

In [16]:
df28

,State,District,Occupation Group,Credit Crores
4,Andaman and Nicobar Islands,Nicobars,Industry,0.0978
5,Andaman and Nicobar Islands,Nicobars,Trade,2.1265
7,Andaman and Nicobar Islands,Nicobars,Transport Operators,0.4751
12,Andaman and Nicobar Islands,Nicobars,Industry,0.3935
13,Andaman and Nicobar Islands,Nicobars,Industry,0.0708
...,...,...,...,...
177686,West Bengal,Uttar Dinajpur,Trade,0.2788
177687,West Bengal,Uttar Dinajpur,Professional And Other Services,0.0101
177688,West Bengal,Uttar Dinajpur,Professional And Other Services,6.3039
177689,West Bengal,Uttar Dinajpur,Professional And Other Services,0.0094
177692,West Bengal,Uttar Dinajpur,Transport Operators,0.4973

In [17]:
df28.columns.tolist()

['State', 'District', 'Occupation Group', 'Credit Crores']

In [18]:
print(df28.columns.tolist())

['State', 'District', 'Occupation Group', 'Credit Crores']

In [19]:
df28.info()

<class 'pandas.core.frame.DataFrame'>
Index: 120387 entries, 4 to 177692
Data columns (total 4 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   State             120387 non-null  object
 1   District          120387 non-null  object
 2   Occupation Group  120387 non-null  object
 3   Credit Crores     120387 non-null  float64
dtypes: float64(1), object(3)
memory usage: 4.6+ MB

In [20]:
df29 = df28.groupby(['State', 'District'])['Credit Crores'].sum()

In [21]:
df29

State                        District
Andaman and Nicobar Islands  Nicobars                       6.5199
                             North and Middle Andaman      59.5272
                             South Andamans              1004.0184
Andhra Pradesh               Alluri Sitharama Raju        119.5107
                             Anakapalli                  1778.1163
                                                           ...
West Bengal                  Purba Bardhaman             6248.9211
                             Purba Medinipur             5366.4463
                             Purulia                     1372.4250
                             South 24 Parganas           6268.9637
                             Uttar Dinajpur              3050.7693
Name: Credit Crores, Length: 781, dtype: float64

In [22]:
df30 = pd.read_csv('/content/drive/MyDrive/MSME Project Datasets/District wise msmes.csv')
df30

,Country,State,District,Year,Calendar Day,"Number Of Micro Enterprise Registered Under Msme (UOM:Number), Scaling Factor:1","Number Of Small Enterprise Registered Under Msme (UOM:Number), Scaling Factor:1","Number Of Medium Enterprise Registered Under Msme (UOM:Number), Scaling Factor:1","Number Of Total Enterprise Registered Under Msme (UOM:Number), Scaling Factor:1"
0,India,Andaman and Nicobar Islands,Nicobars,"Calendar Year (Jan - Dec), 2026",2026-03-14,704,2,0,706
1,India,Andaman and Nicobar Islands,North and Middle Andaman,"Calendar Year (Jan - Dec), 2026",2026-03-14,2879,4,0,2883
2,India,Andaman and Nicobar Islands,South Andamans,"Calendar Year (Jan - Dec), 2026",2026-03-14,15023,152,4,15179
3,India,Andhra Pradesh,Alluri Sitharama Raju,"Calendar Year (Jan - Dec), 2026",2026-03-14,8983,7,1,8991
4,India,Andhra Pradesh,Anakapalli,"Calendar Year (Jan - Dec), 2026",2026-03-14,41551,110,5,41666
...,...,...,...,...,...,...,...,...,...
774,India,West Bengal,Purba Bardhaman,"Calendar Year (Jan - Dec), 2026",2026-03-14,103643,1073,29,104745
775,India,West Bengal,Purba Medinipur,"Calendar Year (Jan - Dec), 2026",2026-03-14,145061,1093,32,146186
776,India,West Bengal,Purulia,"Calendar Year (Jan - Dec), 2026",2026-03-14,36269,231,7,36507
777,India,West Bengal,South 24 Parganas,"Calendar Year (Jan - Dec), 2026",2026-03-14,179899,1029,112,181040
778,India,West Bengal,Uttar Dinajpur,"Calendar Year (Jan - Dec), 2026",2026-03-14,62311,574,15,62900

In [23]:
print(df30.columns.tolist())

['Country', 'State', 'District', 'Year', 'Calendar Day', 'Number Of Micro Enterprise Registered Under Msme (UOM:Number), Scaling Factor:1', 'Number Of Small Enterprise Registered Under Msme (UOM:Number), Scaling Factor:1', 'Number Of Medium Enterprise Registered Under Msme (UOM:Number), Scaling Factor:1', 'Number Of Total Enterprise Registered Under Msme (UOM:Number), Scaling Factor:1']

In [24]:
df31 = df30.drop(['Country','Year', 'Calendar Day', 'Number Of Micro Enterprise Registered Under Msme (UOM:Number), Scaling Factor:1', 'Number Of Small Enterprise Registered Under Msme (UOM:Number), Scaling Factor:1', 'Number Of Medium Enterprise Registered Under Msme (UOM:Number), Scaling Factor:1'] , axis=1)

In [25]:
df31

,State,District,"Number Of Total Enterprise Registered Under Msme (UOM:Number), Scaling Factor:1"
0,Andaman and Nicobar Islands,Nicobars,706
1,Andaman and Nicobar Islands,North and Middle Andaman,2883
2,Andaman and Nicobar Islands,South Andamans,15179
3,Andhra Pradesh,Alluri Sitharama Raju,8991
4,Andhra Pradesh,Anakapalli,41666
...,...,...,...
774,West Bengal,Purba Bardhaman,104745
775,West Bengal,Purba Medinipur,146186
776,West Bengal,Purulia,36507
777,West Bengal,South 24 Parganas,181040
778,West Bengal,Uttar Dinajpur,62900

In [26]:
df32 = df31.rename(columns={'Number Of Total Enterprise Registered Under Msme (UOM:Number), Scaling Factor:1' :'Total MSME'})

In [27]:
df32

                           State                  District  Total MSME
0    Andaman and Nicobar Islands                  Nicobars         706
1    Andaman and Nicobar Islands  North and Middle Andaman        2883
2    Andaman and Nicobar Islands            South Andamans       15179
3                 Andhra Pradesh     Alluri Sitharama Raju        8991
4                 Andhra Pradesh                Anakapalli       41666
..                           ...                       ...         ...
774                  West Bengal           Purba Bardhaman      104745
775                  West Bengal           Purba Medinipur      146186
776                  West Bengal                   Purulia       36507
777                  West Bengal         South 24 Parganas      181040
778                  West Bengal            Uttar Dinajpur       62900

[779 rows x 3 columns]

In [28]:
df33 = pd.merge(df29, df32, on='District')

In [29]:
df33

,District,Credit Crores,State,Total MSME
0,Nicobars,6.5199,Andaman and Nicobar Islands,706
1,North and Middle Andaman,59.5272,Andaman and Nicobar Islands,2883
2,South Andamans,1004.0184,Andaman and Nicobar Islands,15179
3,Alluri Sitharama Raju,119.5107,Andhra Pradesh,8991
4,Anakapalli,1778.1163,Andhra Pradesh,41666
...,...,...,...,...
788,Purba Bardhaman,6248.9211,West Bengal,104745
789,Purba Medinipur,5366.4463,West Bengal,146186
790,Purulia,1372.4250,West Bengal,36507
791,South 24 Parganas,6268.9637,West Bengal,181040
792,Uttar Dinajpur,3050.7693,West Bengal,62900

In [30]:
df33

,District,Credit Crores,State,Total MSME
0,Nicobars,6.5199,Andaman and Nicobar Islands,706
1,North and Middle Andaman,59.5272,Andaman and Nicobar Islands,2883
2,South Andamans,1004.0184,Andaman and Nicobar Islands,15179
3,Alluri Sitharama Raju,119.5107,Andhra Pradesh,8991
4,Anakapalli,1778.1163,Andhra Pradesh,41666
...,...,...,...,...
788,Purba Bardhaman,6248.9211,West Bengal,104745
789,Purba Medinipur,5366.4463,West Bengal,146186
790,Purulia,1372.4250,West Bengal,36507
791,South 24 Parganas,6268.9637,West Bengal,181040
792,Uttar Dinajpur,3050.7693,West Bengal,62900

In [34]:
df33["Credit_Lakh_Msme"] = (df33["Credit Crores"] * 100) / df33["Total MSME"]

In [35]:
df33

,District,Credit Crores,State,Total MSME,Credit_Lakh_Msme
0,Nicobars,6.5199,Andaman and Nicobar Islands,706,0.923499
1,North and Middle Andaman,59.5272,Andaman and Nicobar Islands,2883,2.064766
2,South Andamans,1004.0184,Andaman and Nicobar Islands,15179,6.614523
3,Alluri Sitharama Raju,119.5107,Andhra Pradesh,8991,1.329226
4,Anakapalli,1778.1163,Andhra Pradesh,41666,4.267547
...,...,...,...,...,...
788,Purba Bardhaman,6248.9211,West Bengal,104745,5.965842
789,Purba Medinipur,5366.4463,West Bengal,146186,3.670971
790,Purulia,1372.4250,West Bengal,36507,3.759348
791,South 24 Parganas,6268.9637,West Bengal,181040,3.462751
792,Uttar Dinajpur,3050.7693,West Bengal,62900,4.850190

In [37]:
# Rounding the ratio
df33['Credit_Lakh_Msme'] = df33['Credit_Lakh_Msme'].round(2)

# Ensuring Credit is Float and MSME is Integer (saves RAM)
df33['Credit Crores'] = df33['Credit Crores'].astype(float).round(2)
df33['Total MSME'] = df33['Total MSME'].astype(int)

In [38]:
df33

,District,Credit Crores,State,Total MSME,Credit_Lakh_Msme
0,Nicobars,6.52,Andaman and Nicobar Islands,706,0.92
1,North and Middle Andaman,59.53,Andaman and Nicobar Islands,2883,2.06
2,South Andamans,1004.02,Andaman and Nicobar Islands,15179,6.61
3,Alluri Sitharama Raju,119.51,Andhra Pradesh,8991,1.33
4,Anakapalli,1778.12,Andhra Pradesh,41666,4.27
...,...,...,...,...,...
788,Purba Bardhaman,6248.92,West Bengal,104745,5.97
789,Purba Medinipur,5366.45,West Bengal,146186,3.67
790,Purulia,1372.42,West Bengal,36507,3.76
791,South 24 Parganas,6268.96,West Bengal,181040,3.46
792,Uttar Dinajpur,3050.77,West Bengal,62900,4.85

In [39]:
df34 = pd.read_csv("/content/drive/MyDrive/MSME Project Datasets/Aspirational Distrcit wise msme.csv")

In [42]:
df34

,Country,State,District,Year,As On Date,"Aspirational District Wise Number Of Micro Enterprises (UOM:Number), Scaling Factor:1","Aspirational District Wise Number Of Small Enterprises (UOM:Number), Scaling Factor:1","Aspirational District Wise Number Of Medium Enterprises (UOM:Number), Scaling Factor:1","Aspirational District Wise Number Of Total Micro, Small, And Medium Enterprises (Msmes) (UOM:Number), Scaling Factor:1"
0,India,Andhra Pradesh,Visakhapatnam,"Calendar Year (Jan - Dec), 2026",14-Mar-2026,125271,1849,154,127274
1,India,Andhra Pradesh,Vizianagaram,"Calendar Year (Jan - Dec), 2026",14-Mar-2026,57913,364,19,58296
2,India,Andhra Pradesh,Y.S.R.,"Calendar Year (Jan - Dec), 2026",14-Mar-2026,108125,734,28,108887
3,India,Arunachal Pradesh,Namsai,"Calendar Year (Jan - Dec), 2026",14-Mar-2026,2502,10,0,2512
4,India,Assam,Baksa,"Calendar Year (Jan - Dec), 2026",14-Mar-2026,18822,38,4,18864
...,...,...,...,...,...,...,...,...,...
112,India,West Bengal,Birbhum,"Calendar Year (Jan - Dec), 2026",14-Mar-2026,71967,501,13,72481
113,India,West Bengal,Dakshin Dinajpur,"Calendar Year (Jan - Dec), 2026",14-Mar-2026,30371,168,5,30544
114,India,West Bengal,Malda,"Calendar Year (Jan - Dec), 2026",14-Mar-2026,88870,481,15,89366
115,India,West Bengal,Murshidabad,"Calendar Year (Jan - Dec), 2026",14-Mar-2026,143676,842,27,144545
116,India,West Bengal,Nadia,"Calendar Year (Jan - Dec), 2026",14-Mar-2026,113662,590,14,114266

In [43]:
print(df34.columns.tolist())

['Country', 'State', 'District', 'Year', 'As On Date', 'Aspirational District Wise Number Of Micro Enterprises (UOM:Number), Scaling Factor:1', 'Aspirational District Wise Number Of Small Enterprises (UOM:Number), Scaling Factor:1', 'Aspirational District Wise Number Of Medium Enterprises (UOM:Number), Scaling Factor:1', 'Aspirational District Wise Number Of Total Micro, Small, And Medium Enterprises (Msmes) (UOM:Number), Scaling Factor:1']

In [45]:
df35 = df34.drop(['Country', 'State', 'Year', 'As On Date', 'Aspirational District Wise Number Of Micro Enterprises (UOM:Number), Scaling Factor:1', 'Aspirational District Wise Number Of Small Enterprises (UOM:Number), Scaling Factor:1', 'Aspirational District Wise Number Of Medium Enterprises (UOM:Number), Scaling Factor:1', 'Aspirational District Wise Number Of Total Micro, Small, And Medium Enterprises (Msmes) (UOM:Number), Scaling Factor:1'] , axis = 1)

In [46]:
df35

             District
0       Visakhapatnam
1        Vizianagaram
2              Y.S.R.
3              Namsai
4               Baksa
..                ...
112           Birbhum
113  Dakshin Dinajpur
114             Malda
115       Murshidabad
116             Nadia

[117 rows x 1 columns]

In [51]:
df33['Is_Aspirational'] = df33['District'].isin(df35['District'])

In [52]:
df33

,District,Credit Crores,State,Total MSME,Credit_Lakh_Msme,Is_Aspirational
0,Nicobars,6.52,Andaman and Nicobar Islands,706,0.92,False
1,North and Middle Andaman,59.53,Andaman and Nicobar Islands,2883,2.06,False
2,South Andamans,1004.02,Andaman and Nicobar Islands,15179,6.61,False
3,Alluri Sitharama Raju,119.51,Andhra Pradesh,8991,1.33,False
4,Anakapalli,1778.12,Andhra Pradesh,41666,4.27,False
...,...,...,...,...,...,...
788,Purba Bardhaman,6248.92,West Bengal,104745,5.97,False
789,Purba Medinipur,5366.45,West Bengal,146186,3.67,False
790,Purulia,1372.42,West Bengal,36507,3.76,False
791,South 24 Parganas,6268.96,West Bengal,181040,3.46,False
792,Uttar Dinajpur,3050.77,West Bengal,62900,4.85,False

In [53]:
print(df33['Is_Aspirational'].value_counts())

Is_Aspirational
False    676
True     117
Name: count, dtype: int64

In [54]:
mean_val = df33['Credit_Lakh_Msme'].mean()
median_val = df33['Credit_Lakh_Msme'].median()

print(f"National Mean: {mean_val:.2f}")
print(f"National Median: {median_val:.2f}")

National Mean: inf
National Median: 3.84

In [55]:
print(df33['Total MSME'].median())

38423.0

In [67]:

benchmark = 3.84

df33['Gap_Percentage'] = ((df33['Credit_Lakh_Msme'] - benchmark) / benchmark) * 100
df33['Gap_Percentage'] = df33['Gap_Percentage'].round(2)

In [57]:
df33

,District,Credit Crores,State,Total MSME,Credit_Lakh_Msme,Is_Aspirational,Gap_Percentage
0,Nicobars,6.52,Andaman and Nicobar Islands,706,0.92,False,-76.04
1,North and Middle Andaman,59.53,Andaman and Nicobar Islands,2883,2.06,False,-46.35
2,South Andamans,1004.02,Andaman and Nicobar Islands,15179,6.61,False,72.14
3,Alluri Sitharama Raju,119.51,Andhra Pradesh,8991,1.33,False,-65.36
4,Anakapalli,1778.12,Andhra Pradesh,41666,4.27,False,11.20
...,...,...,...,...,...,...,...
788,Purba Bardhaman,6248.92,West Bengal,104745,5.97,False,55.47
789,Purba Medinipur,5366.45,West Bengal,146186,3.67,False,-4.43
790,Purulia,1372.42,West Bengal,36507,3.76,False,-2.08
791,South 24 Parganas,6268.96,West Bengal,181040,3.46,False,-9.90
792,Uttar Dinajpur,3050.77,West Bengal,62900,4.85,False,26.30

In [59]:
df33

,District,Credit Crores,State,Total MSME,Credit_Lakh_Msme,Is_Aspirational,Gap_Percentage
0,Nicobars,6.52,Andaman and Nicobar Islands,706,0.92,False,-76.04
1,North and Middle Andaman,59.53,Andaman and Nicobar Islands,2883,2.06,False,-46.35
2,South Andamans,1004.02,Andaman and Nicobar Islands,15179,6.61,False,72.14
3,Alluri Sitharama Raju,119.51,Andhra Pradesh,8991,1.33,False,-65.36
4,Anakapalli,1778.12,Andhra Pradesh,41666,4.27,False,11.20
...,...,...,...,...,...,...,...
788,Purba Bardhaman,6248.92,West Bengal,104745,5.97,False,55.47
789,Purba Medinipur,5366.45,West Bengal,146186,3.67,False,-4.43
790,Purulia,1372.42,West Bengal,36507,3.76,False,-2.08
791,South 24 Parganas,6268.96,West Bengal,181040,3.46,False,-9.90
792,Uttar Dinajpur,3050.77,West Bengal,62900,4.85,False,26.30

In [61]:
import numpy as np
df33['Credit_Lakh_Msme'] = df33['Credit_Lakh_Msme'].replace([np.inf, -np.inf], 0)
df33

,District,Credit Crores,State,Total MSME,Credit_Lakh_Msme,Is_Aspirational,Gap_Percentage
0,Nicobars,6.52,Andaman and Nicobar Islands,706,0.92,False,-76.04
1,North and Middle Andaman,59.53,Andaman and Nicobar Islands,2883,2.06,False,-46.35
2,South Andamans,1004.02,Andaman and Nicobar Islands,15179,6.61,False,72.14
3,Alluri Sitharama Raju,119.51,Andhra Pradesh,8991,1.33,False,-65.36
4,Anakapalli,1778.12,Andhra Pradesh,41666,4.27,False,11.20
...,...,...,...,...,...,...,...
788,Purba Bardhaman,6248.92,West Bengal,104745,5.97,False,55.47
789,Purba Medinipur,5366.45,West Bengal,146186,3.67,False,-4.43
790,Purulia,1372.42,West Bengal,36507,3.76,False,-2.08
791,South 24 Parganas,6268.96,West Bengal,181040,3.46,False,-9.90
792,Uttar Dinajpur,3050.77,West Bengal,62900,4.85,False,26.30

In [63]:
#to assign priority that where should a bank look up to
def assign_priority(row):
    if row['Gap_Percentage'] < -50 and row['Is_Aspirational'] == True:
        return "1. Critical (Aspirational Desert)"
    elif row['Gap_Percentage'] < -50:
        return "2. High Gap"
    elif row['Gap_Percentage'] < 0:
        return "3. Underfunded"
    else:
        return "4. Stable"

df33['Priority_Level'] = df33.apply(assign_priority, axis=1)

In [64]:
df33

,District,Credit Crores,State,Total MSME,Credit_Lakh_Msme,Is_Aspirational,Gap_Percentage,Priority_Level
0,Nicobars,6.52,Andaman and Nicobar Islands,706,0.92,False,-76.04,2. High Gap
1,North and Middle Andaman,59.53,Andaman and Nicobar Islands,2883,2.06,False,-46.35,3. Underfunded
2,South Andamans,1004.02,Andaman and Nicobar Islands,15179,6.61,False,72.14,4. Stable
3,Alluri Sitharama Raju,119.51,Andhra Pradesh,8991,1.33,False,-65.36,2. High Gap
4,Anakapalli,1778.12,Andhra Pradesh,41666,4.27,False,11.20,4. Stable
...,...,...,...,...,...,...,...,...
788,Purba Bardhaman,6248.92,West Bengal,104745,5.97,False,55.47,4. Stable
789,Purba Medinipur,5366.45,West Bengal,146186,3.67,False,-4.43,3. Underfunded
790,Purulia,1372.42,West Bengal,36507,3.76,False,-2.08,3. Underfunded
791,South 24 Parganas,6268.96,West Bengal,181040,3.46,False,-9.90,3. Underfunded
792,Uttar Dinajpur,3050.77,West Bengal,62900,4.85,False,26.30,4. Stable

In [65]:
print(df33['Priority_Level'].value_counts())

Priority_Level
4. Stable                            399
3. Underfunded                       290
2. High Gap                           84
1. Critical (Aspirational Desert)     20
Name: count, dtype: int64

In [68]:
df33.to_csv('India_MSME_Credit_Gap_2026.csv', index=False)

In [69]:
print(df33[df33['Credit_Lakh_Msme'] == 0]['District'].unique())
print(df33[df33['Credit_Lakh_Msme'] == 0].shape[0])

['Unknown Districts Of India']
10

In [71]:
df33 = df33[df33['District'] != 'Unknown Districts Of India']

In [72]:
df33.shape

(775, 8)

In [74]:
print(df33.columns.tolist())

['District', 'Credit Crores', 'State', 'Total MSME', 'Credit_Lakh_Msme', 'Is_Aspirational', 'Gap_Percentage', 'Priority_Level']

In [75]:
print(df33[df33['Priority_Level'] == '1. Critical (Aspirational Desert)'].sort_values('Gap_Percentage').head(10))

       District  Credit Crores              State  Total MSME  \
431     Chandel           8.34            Manipur        2097
55        Baksa         108.76              Assam       18864
470     Kiphire          10.39           Nagaland        1441
593   Gyalshing          22.87             Sikkim        2252
87     Udalguri         232.11              Assam       20025
157       Sukma          29.90       Chhattisgarh        2564
133     Bijapur          39.06       Chhattisgarh        3097
69   Hailakandi         265.41              Assam       20195
220         Nuh         479.35            Haryana       35982
43       Namsai          33.93  Arunachal Pradesh        2512

     Credit_Lakh_Msme  Is_Aspirational  Gap_Percentage  \
431              0.40             True          -89.58
55               0.58             True          -84.90
470              0.72             True          -81.25
593              1.02             True          -73.44
87               1.16             True          -69.79
157              1.17             True          -69.53
133              1.26             True          -67.19
69               1.31             True          -65.89
220              1.33             True          -65.36
43               1.35             True          -64.84

                        Priority_Level
431  1. Critical (Aspirational Desert)
55   1. Critical (Aspirational Desert)
470  1. Critical (Aspirational Desert)
593  1. Critical (Aspirational Desert)
87   1. Critical (Aspirational Desert)
157  1. Critical (Aspirational Desert)
133  1. Critical (Aspirational Desert)
69   1. Critical (Aspirational Desert)
220  1. Critical (Aspirational Desert)
43   1. Critical (Aspirational Desert)

In [76]:
df33.to_csv('Indian_MSME_Credit_Gap_2026.csv', index=False)